.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. californium_qt test_californium_qt
clean: FORCE
	$(MAKE) -C .. californium_qt_clean test_californium_qt_clean
check: FORCE
	$(MAKE) -C .. test_californium_qt_check
californium-qt californium-qt.exe: FORCE
	 $(MAKE) -C .. californium_qt
